version: '3.1'
services:
  stats-server:
    build: ./stats
    container_name: ewm-stats
    restart: always
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_stats_db:5432/ewm_stats?user=postgres&password=iamroot
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ./server
    container_name: ewm-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_service_db:5432/ewm?user=postgres&password=iamroot

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_service_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot