CREATE SCHEMA IF NOT EXISTS ewm_stats;
CREATE TABLE IF NOT EXISTS ewm_stats.stat
(
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(255)                         NOT NULL,
    uri       VARCHAR(255)                         NOT NULL,
    ip        VARCHAR(512)                         NOT NULL,
    timestamp TIMESTAMP                            NOT NULL,
    CONSTRAINT pk_stat PRIMARY KEY (id)
);